### ISSUE TITLE
Data set

### ISSUE THREAD

**Issue by sabrinaschmid** [sabrinaschmid/capstone-project#1]
### Value statement

As a user
I need dishes with a title, an image, ingredients and details about intolerances
so that I can make a decision about which meal to choose with the app's help.

### Description (Text, Scribble, Wireframe, Design)
**Structure:**

- title
- translated title
- ingredients
- intolerance-info
- eating-style-info 

### Tasks

- [x] Choose a country

- [x] Write down 15 dishes for a menu

- [x] Translate the title

- [x] List all ingredients

- [x] List info about intolerances

- [x] Find free images for each dish

- [x] Create the structure for the data objects

### Size

medium
