### ISSUE TITLE
Restful Routing

### ISSUE THREAD

**Issue by sabrinaschmid** [sabrinaschmid/capstone-project#11]
### Value statement

As a user
I need to see different pages within the app
so that I have a better orientation and dont't have to scroll that much.

### Description (Text, Scribble, Wireframe, Design)
Include Restful Routing into the project.

Feature-branch "dishdetail"

### Acceptance criteria

- [x] There are different routes for the homepage and the detail page

- [x] The user can navigate back and forth

### Tasks
- [x] Include routing into the App-Compontent

- [x] Make sample detail page to have a second route to work with

- [x] Include restful routing with the dishID as the URL-Parameter of the detail page

- [x] Access the dish data on the detail page (param, match)

- [x] Test on mobile

### Size
big
