### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by sabrinaschmid** [sabrinaschmid/capstone-project#13]
### Value statement

As a user
I need a header at the top of the app page
so that I know which app I am using and what page within the app I am currently on.

### Description (Text, Scribble, Wireframe, Design)
- Add a fixed header with an logo and the name of the app

Feature-branch "header"

### Acceptance criteria

- [x] The header's position is fixed

- [x] The header exists on every route/page

- [x] There is a app logo and a app name

### Tasks

- [x] Integrate Page Layout Component with a header 

- [x] Add styling

- [x] Test on mobile 

### Size
small
