### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by sabrinaschmid** [sabrinaschmid/capstone-project#16]
### Value statement

As a user
I need to view the app in the browser
so that I can acces it via my device.

### Description (Text, Scribble, Wireframe, Design)
Deploy the app onto a public domain.

### Acceptance criteria

- [x] The app runs on a domain

### Tasks

- [x] Use Firebase Hosting

- [x] Test on mobile

### Size
small
