### ISSUE TITLE
Dish

### ISSUE THREAD

**Issue by sabrinaschmid** [sabrinaschmid/capstone-project#2]
### Value statement

As a user
I need to see dishes with basic information 
so that I can choose if I want detailed information about the dish.

### Description (Text, Scribble, Wireframe, Design)
A short dish entry that gives an overview to the user. If multiple dishes are rendered, they form a vertical list.
![Home](https://user-images.githubusercontent.com/59568064/75857252-273f0180-5df6-11ea-99a3-5a1d70c446ff.jpg)

Feature-branch "dishlist"

### Acceptance criteria

- [x] A list entry includes a picture, the title, intolerance and eating-style info

- [x] List entries have to be visually separated

- [x] You can scroll the list vertically

- [x] The tag "vegan" is shown if the value is true, the tag "vegetarisch" is shown if the value is true. If the dish is neither vegan nor vegetarian, no tag is rendered

- [x] The intolerance badges have different text and colors regarding if a dish is suitable for the intolerance

### Tasks

- [x] Create dishlist component

- [x] Create dish component

- [x] Add styling

- [x] Add logic for rendering eating-style

- [x] Add logic for intolerance-badges

- [x] Add data

- [x] Test on mobile 

### Size
big
