### ISSUE TITLE
Add toggle element for intolerances on detail page

### ISSUE THREAD

**Issue by sabrinaschmid** [sabrinaschmid/capstone-project#21]
As a user
I need to see critical ingredients for my intolerance
so that I have enough information to make my decision on eating the dish or not.

### Description (Text, Scribble, Wireframe, Design)
Each intolerance has one box on the detail page that shows critical ingredients when the user clicks on the box.
![ToggleIngredients](https://user-images.githubusercontent.com/59568064/76689718-ec7c6b00-6638-11ea-8eea-2e2e4f3b5689.jpg)

### Acceptance criteria

- [x] The user can click on each box and the box expands. The expanded part shows critical ingredients

- [x] The user can click on an expanded box and the ingredients disappear.

### Tasks

- [x] Create toggle logic

- [x] Create boxes with logic to render the critical ingredients

- [x] Add styling

- [x] Create new Icons

- [x] Test on mobile

### Size
