### ISSUE TITLE
Show pictures via Firebase Storage

### ISSUE THREAD

**Issue by sabrinaschmid** [sabrinaschmid/capstone-project#23]
As a user 
I need to see a picture of the dish
so that I know what kind of a dish to expect before ordering it.

### Description (Text, Scribble, Wireframe, Design)
Show one picture for each dish on the dishlist and the detail page

### Acceptance criteria

- [x] The user can see a picture of the dish in the app

### Tasks

- [x] Upload pictures in Firebase storage

- [x] Include a reference in the firestore database so that I can link elements

- [x] Download pictures for dishlist and singleDish 

- [x] Test on mobile

### Size
big
