### ISSUE TITLE
Back Button for detail page

### ISSUE THREAD

**Issue by sabrinaschmid** [sabrinaschmid/capstone-project#24]
As a user
I need back button on the detail page 
so that I can get back to the homepage.

### Description (Text, Scribble, Wireframe, Design)
Back button on the left side of the header on the detail page.

### Acceptance criteria

- [x] The user can tap on the back button to get back to the homepage

### Tasks

- [x] Refactor Header

- [x] Show app logo only in the header on the homepage

- [x] Include back button into the header on the detail page

- [x] Styling

- [x] Test on mobile

### Size
medium
