### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by sabrinaschmid** [sabrinaschmid/capstone-project#25]
### Description (Text, Scribble, Wireframe, Design)
Show footer with copyright and font-/icon infos

### Acceptance criteria

- [x] Footer is at the bottom of every page

### Tasks

- [x]  Write footer component

- [x] Write text for footer

- [x] Styling

- [x] Test on mobile

### Size
