### ISSUE TITLE
Live Search

### ISSUE THREAD

**Issue by sabrinaschmid** [sabrinaschmid/capstone-project#3]
### Value statement

As a user
I need to search for a dish 
so that I can see if the app has information about the dish I am looking for.

### Description (Text, Scribble, Wireframe, Design)
A search with an input field for the dish, a form element for the country and a reset-button.
![Home](https://user-images.githubusercontent.com/59568064/75624414-274fbf00-5bb4-11ea-82fb-c00d9268e79c.jpg)

### Acceptance criteria

- [x] The user can use Tab to walk through the form

- [x] "No results" in case the user searches for an unknown dish

- [x] The input field is required

- [x] The reset button clears the input field and the filtered dishlist

### Tasks

- [x] Create an input 

- [x] Create a reset button

- [x] Show a filtered search result of dishes below the search

- [x] Change list headline from "Alle Gerichte" to "Dein Suchergebnis" when the user types something in

- [x] Create a "no results" message including the typed in letters

- [x] Add styling

- [x] Test on mobile 

### Size
big
