### ISSUE TITLE
Search Optimization

### ISSUE THREAD

**Issue by sabrinaschmid** [sabrinaschmid/capstone-project#32]
### Value statement

As a user
I need to see my search results after returning to the homepage from a detail page
so that I do not have to retype my search phrase all the time

### Description (Text, Scribble, Wireframe, Design)
The input field and search results should be stored so that they are still visible after returning to the homepage via the back button.

### Acceptance criteria

- [x] The search phrase is visible as a queryString in the URL

- [x] When returning from the detail page, the input still shows the search phrase, the search results are still there and the queryString is shown in the URL

- [x] Input, field, search results and URL are cleared after using the reset button 

### Tasks
- [x] Write the search phrase as a queryString into the URL

- [x] Store the data 

- [x] Adjust the reset button so that it resets the URL

- [x] Test on mobile
