### ISSUE TITLE
Usability optimization of the search component on submit

### ISSUE THREAD

**Issue by sabrinaschmid** [sabrinaschmid/capstone-project#34]
### Value statement

As a mobile user
I need to see the search results after typing
so that I can see if my search was successful

### Description (Text, Scribble, Wireframe, Design)
- Close the keyboard after submit
- Scroll to the first search result after submit because the mobile keyboard covers the search result so that the user can't see that the list entries change

### Acceptance criteria
- [x] On submit the keyboard closes

- [x] On submit the user is guided to the first search result

- [x] With a tap into the input field, the keyboard appears

### Tasks

- [x] Close keyboard on submit

- [x] Scroll to first search result

- [x] Mobile testing on different phones and browsers

### Size
medium
