### ISSUE TITLE
Scroll-to-top button

### ISSUE THREAD

**Issue by sabrinaschmid** [sabrinaschmid/capstone-project#35]
### Value statement

As a user
I need a button that brings me to the top of the page
so that I do not have to scroll a lot on long pages.

### Description (Text, Scribble, Wireframe, Design)
Add a scroll to top button on every page.

### Acceptance criteria

- [x] Button is sticky in the bottom right corner of all pages

- [x] On button click the pages scrolls to the top smoothly

### Tasks

- [x] Add button component

- [x] Integrate smooth scrolling with useSpring

- [x] Add styling

- [x] Test on mobile

### Size
small
