### ISSUE TITLE
Detail page

### ISSUE THREAD

**Issue by sabrinaschmid** [sabrinaschmid/capstone-project#4]
### Value statement

As a user
I need to see detailed information about the dish and its ingredients
so that I can make a decision about being able to eat it or not.

### Description (Text, Scribble, Wireframe, Design)
The detail page includes the name of the dish in the original language, a translation of the name, a picture, information about intolerances and ingredients.
![Detail Page](https://user-images.githubusercontent.com/59568064/75625075-d42d3a80-5bba-11ea-9460-f41950ae4ac9.jpg)

### Acceptance criteria
- [x] The user can leave the detail page and return to his/her search result

### Tasks

- [x] Create a headline with the title of the dish

- [x] Show the translation of the name of the dish

- [x] Show an unordered list of ingredients

- [x] Show information about the dish being okay or not for the existing intolerances

- [x] Show information about the dish being okay or not for the existing eating-styles

- [x] Routing

- [x] Add styling

- [x] Test on mobile 

### Size
big
