### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by sabrinaschmid** [sabrinaschmid/capstone-project#6]
### Value statement

As a user
I need info about multiply dishes 
so that I can get informed about their ingredients regarding my intolerance and eating-style.

### Description (Text, Scribble, Wireframe, Design)
Set up firebase (feature-branch "firebase-setup") for the project.

### Acceptance criteria

- [x] The written data set is in the project (Get)

- [x] Data can be changed (Post, Patch, Delete)

### Tasks

- [x] Integrate firebase into the project

- [x] Integrate my data set 

### Size
medium

**Comment by sabrinaschmid** [comment]
### Value statement

As a user
I need info about multiply dishes 
so that I can get informed about their ingredients regarding my intolerance and eating-style.

### Description (Text, Scribble, Wireframe, Design)


### Acceptance criteria

- [ ] The written data set is in the project (Get)

- [ ] Data can be changed (Post, Patch, Delete)

### Tasks

- [ ] Integrate mongoose into the project

- [ ] Include my data set 


### Size
medium
