### ISSUE TITLE
Save state

### ISSUE THREAD

**Issue by sabrinaschmid** [sabrinaschmid/capstone-project#7]

**Comment by sabrinaschmid** [comment]
### Value statement

As a user
I need to keep my configured filters (intolerances and eating-style) throughout sessions
so that I don't loose my valuable customizations

### Description (Text, Scribble, Wireframe, Design)
The chosen filters are still active when the user returns to the search result page (from an external site or from the detail page). 

### Acceptance criteria

- [ ] The user can leave the page and can still see his/her last search including set filters after returning

- [ ] The user can return to the search page from a deatail page and can still see his/her last search including set filters

- Reload of the page should load search including filters

### Tasks

- [ ] Implement save/load for search

- [ ] Test on desktop and mobile


### Size
medium
